// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwaeldxeuqxzcohnflun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YWVsZHhldXF4emNvaG5mbHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTQyNjYsImV4cCI6MjA2NjQzMDI2Nn0.Mq1BIhsvpT78f5TNqXaejRSnERehVfo9teJ_lk-UllY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});